### ISSUE TITLE
Can i generate RSA Public key and private key in Swift

### ISSUE THREAD

**Issue by calvinsug** [TakeScoop/SwiftyRSA#106]
Does this library implement `SecKeyGeneratePair` to generate key pair for public key and private key ? I need to generate different key pair for each device and i would like to generate it when user attempt to login. So, are there any way to generate key pair from the swift code instead generate from my terminal ?

**Comment by ldiqual** [comment]
@calvinsug SwiftyRSA doesn't offer key generation but it seems like something that should be offered. The primary goal of the library is to import existing keys because that's what hard to do. I'm happy to review any PR that would help getting us to something like `SwiftyRSA.generateKeyPair(padding: ...) -> (PublicKey, PrivateKey)`.

**Comment by 4taras4** [comment]
You can use my library for generating RSA keys
https://github.com/4taras4/RSASwiftGenerator
