### ISSUE TITLE
 can support  public key decrypt ?

### ISSUE THREAD

**Issue by Destinyxl** [TakeScoop/SwiftyRSA#110]

**Comment by ldiqual** [comment]
@FXLynn This doesn't seem like a common pattern in public key cryptography, do you have a specific example of what you're trying to do? Maybe are you thinking about [signing](https://github.com/TakeScoop/SwiftyRSA#sign-with-a-private-key)?

**Comment by Destinyxl** [comment]
We use RSA to communicate encrypted with the server, sometimes， the server will return data encrypted with the private key which I need to use the public key to decrypt it

**Comment by ldiqual** [comment]
@Destinyxl Sorry for the delay on this. I might be wrong, but in the case you describe above (encrypt with private key, decrypt with public key), I believe the encryption itself has no effect because an attacker intercepting the encrypted message would have access to the public key (since public keys are meant to be shared). The way public-key cryptography works is by [encrypting with the public key](https://en.wikipedia.org/wiki/Public-key_cryptography#Public_Key_Encryption) (which is shared) and decrypting with the private key. This way if an attacker intercepts a message, they have no way to decrypt it because the private key is not shared. I believe that 

Please feel free to re-open the issue if you feel like you have another use-case where this method seems fitting. Thanks!
