### ISSUE TITLE
Xcode 10 beta and swift 4:  error when compile

### ISSUE THREAD

**Issue by luky0007** [TakeScoop/SwiftyRSA#124]
SwifyRSA not working on Xcode 10, there are 2 compile error:
1. `PublicKey.swift:103:25: Cannot invoke initializer for type 'Range<String.Index>' with an argument list of type '(Range<String.Index>)'`
2. `module.modulemap:9:12: Header 'SwiftyRSA-Swift.h' not found`

**Comment by mx-web** [comment]
Have these errors too

**Comment by nabbestemmia** [comment]
I have the same errors, I guess we need to wait for a new version of this pod to fix them

**Comment by popenke** [comment]
Same here 😞.

**Comment by nabbestemmia** [comment]
I "solved" the problem by simply downloading the whole project and importing the content of "SwiftyRSA" folder into mine, without info.plist file and adding "NSData+SHA.h" to my bridging file

**Comment by ldiqual** [comment]
We won't publish a Swift 4.2-compatible versionn of SwiftyRSA until Xcode 10 GM comes out because the language / SDK might still evolve. However the `master` branch contains a fix for this specific error and you can use this branch when integrating with cocoapods in the meantime.

Fixed by https://github.com/TakeScoop/SwiftyRSA/pull/121

**Comment by madnik** [comment]
@ldiqual as GM is out can we tag a release with this fix.

**Comment by dmi3j** [comment]
I think it's about time to release fix.
