### ISSUE TITLE
How to use the public key to decrypt

### ISSUE THREAD

**Issue by lujiamingCode** [TakeScoop/SwiftyRSA#214]

**Comment by DevNathan** [comment]
You can't... That's the point ! 
https://en.wikipedia.org/wiki/Public-key_cryptography

**Comment by lujiamingCode** [comment]
> You can't... That's the point !
> https://en.wikipedia.org/wiki/Public-key_cryptography

Thank you, I have solved it

**Comment by yanxiaobing** [comment]
> You can't... That's the point ! https://en.wikipedia.org/wiki/Public-key_cryptography

Actually it is possible, please refer to https://github.com/ideawu/Objective-C-RSA

**Comment by DevNathan** [comment]
**No
You can't** 

This repo isn't well documented, but by reading it quickly it only enables to encrypt in C with RSA and decrypt in PHP.

I don't know what the encrypt.php does but it CANNOT decrypt a message with the public key 

Indeed, if an algorithm is able to do so, then RSA is broken and half of internet btw. 
However, RSA is a mathématic algorithm, with a proof of security which ensures that only the calculation power (so the quantum machines with Shore's alorgithm) can break it. Today, keys with a length of 2048 bits are strongly secure.
But I insist on the fact that NO ALGORITHM is today able to break RSA-2048.

I really don't know what this script try to do, but it scam
You have to understand that is the beauty of Public key cryptosystems. You have to raise the cipher text received and raise it to the power of the decryption key d while using the N as the mod in order to decrypt the message.

I invite you to look at how RSA works and if you think you find anything which could break it, please develop a mathematic explanation and not a algorithm done by another and undocumented

**Comment by yanxiaobing** [comment]
Thank you for your reply. In fact, RSA should be able to support private key encryption and public key decryption, and public key encryption and private key decryption. That reference I gave you does it. 
`// return base64 encoded string
+ (NSString *)encryptString:(NSString *)str publicKey:(NSString *)pubKey;
// return raw data
+ (NSData *)encryptData:(NSData *)data publicKey:(NSString *)pubKey;
// return base64 encoded string
+ (NSString *)encryptString:(NSString *)str privateKey:(NSString *)privKey;
// return raw data
+ (NSData *)encryptData:(NSData *)data privateKey:(NSString *)privKey;

// decrypt base64 encoded string, convert result to string(not base64 encoded)
+ (NSString *)decryptString:(NSString *)str publicKey:(NSString *)pubKey;
+ (NSData *)decryptData:(NSData *)data publicKey:(NSString *)pubKey;
+ (NSString *)decryptString:(NSString *)str privateKey:(NSString *)privKey;
+ (NSData *)decryptData:(NSData *)data privateKey:(NSString *)privKey;`

Through these APIs, you can get a good understanding of its functions.

**Comment by DevNathan** [comment]
I think your are mixing up `encryption` and `digital signature`

The first one, uses the public key to encrypt and the private key to decrypt. 
The public key CANNOT retrieves the initial message

The second one, uses the PRIVATE key to sign a message and the public key is ABLE to verifiy the digital signature 

But the signature isn't a encryption, so the public key cannot decrypt a message encrypted with the public key (as in symetric encryption) and the private key cannot _encrypt_ a message but only _sign_ it.

I let you read this wikis 

- https://en.wikipedia.org/wiki/Digital_signature
- https://en.wikipedia.org/wiki/Public-key_cryptography
- https://en.wikipedia.org/wiki/RSA_(cryptosystem)

**Comment by yanxiaobing** [comment]
Maybe the instructions for this are more detailed. https://github.com/btnguyen2k/swiftutils/blob/master/README-RSAUtils.md

Watch carefully！
`static func encryptWithRSAPublicKey(data: Data, pubkeyBase64: String, tagName: String) throws -> Data?`

`static func decryptWithRSAPrivateKey(encryptedData: Data, privkeyBase64: String) throws -> Data?`

**Comment by DevNathan** [comment]
yes ? Encryt with the pubkey and decrypt with the privkey 

What's your point ?

I complety agree with this repo saying that 

```
static func encryptWithRSAPublicKey(str: String, pubkeyBase64: String) throws -> Data?: Encrypts a string using RSA public key.

static func encryptWithRSAPublicKey(data: Data, pubkeyBase64: String, tagName: String) throws -> Data?: Encrypts data using RSA public key. Also, the public key will be stored in keychain specified by tagName.

static func encryptWithRSAPublicKey(str: String, pubkeyBase64: String, tagName: String) throws -> Data?: Encrypts a string using RSA public key. Also, the public key will be stored in keychain specified by tagName.

static func decryptWithRSAPrivateKey(encryptedData: Data, privkeyBase64: String) throws -> Data?: Decrypts an encrypted data using a RSA private key.

static func decryptWithRSAPrivateKey(encryptedData: Data, privkeyBase64: String, tagName: String) throws -> Data?: Decrypts an encrypted data using a RSA private key. Also, the private key will be stored in keychain specified by tagName.
```

**Comment by yanxiaobing** [comment]
The wrong reference link was provided earlier. You can watch this https://github.com/btnguyen2k/swift-rsautils#readme.

And watch carefully！
`RSAUtils.encryptWithRSAPrivateKey(data: NSData, privkeyBase64: String, keychainTag: String) -> NSData?`
`RSAUtils.decryptWithRSAPublicKey(encryptedData: NSData, pubkeyBase64: String, keychainTag: String) -> NSData?`

**Comment by DevNathan** [comment]
In fact this function are implemented, but there are not secure and not used in practice 

Just see one of the issue related to this project https://github.com/btnguyen2k/swift-rsautils/issues/13

Again, that's not because a function is named 'decrypt with public key' that you will be able to decrypt a **_securely_** encryted message with the pubkey 

By  **_securely_** I mean encrypted with the pubkey as it always should be

You can do very strange things, if you do not encrypt with the right key and be able to _decrypt_ with a strange method, even if here, _decrypt_ hasn't the right meaning. 
My point is that in the general case, you cannot decrypt a message with pubkey, if it has been encrypted as it is safe to do, ie with a public key and RSA-2048 at least

**Comment by yanxiaobing** [comment]
I agree with you. As we all know, public keys are designed to be exposed, so if we use private key encryption and public key decryption, there is a possibility of information disclosure. But obviously, this method is much safer than plaintext transmission. 

The scenario I encountered is that the server will encrypt the data with the private key and then transmit it to the client, so I need to decrypt the relevant data with the public key. I have communicated with my back-end colleagues related to Java and PHP. They all have relevant implementations of using private key encryption and public key decryption.

Through today's retrieval, including the previously mentioned issue and some other discussions, such as https://developer.apple.com/forums/thread/133689 , I think SwiftRSA, as the best swift ras library, should consider improving the function of private key encryption and public key decryption, even if it is not a best practice in theory. 

Once I complete the relevant implementation, I will be happy to improve it through pr.

**Comment by paulw11** [comment]
> I agree with you. As we all know, public keys are designed to be exposed, so if we use private key encryption and public key decryption, there is a possibility of information disclosure. But obviously, this method is much safer than plaintext transmission.

This is not really correct.  You must assume that the public key is known. Data encrypted with a private key is nothing more than *security by obscurity*.  All you have done is made it more difficult to access your message payload but not changed the security of your message at all.

Where you do use "encryption with the private key" is generating a message signature; You can generate a hash of the message, encrypt this hash with the private key and append that to your message.  The receiver can then generate the same hash, decrypt the encrypted hash and verify that the values are the same.  They then know that the message hasn't been altered and was sent by someone who posses the private key.

**Comment by yanxiaobing** [comment]
> > I agree with you. As we all know, public keys are designed to be exposed, so if we use private key encryption and public key decryption, there is a possibility of information disclosure. But obviously, this method is much safer than plaintext transmission.
> 
> This is not really correct. You must assume that the public key is known. Data encrypted with a private key is nothing more than [_security through obscurity_](https://en.wikipedia.org/wiki/Security_through_obscurity). All you have done is made it more difficult to access your message payload but not changed the security of your message at all.
> 
> Where you do use "encryption with the private key" is generating a message signature; You can generate a hash of the message, encrypt this hash with the private key and append that to your message. The receiver can then generate the same hash, decrypt the encrypted hash and verify that the values are the same. They then know that the message hasn't been altered and was sent by someone who posses the private key.

I agree with you very much. We should not use the scheme of private key encryption and public key decryption. But what I want to say is that other languages have the implementation of private key encryption and public key decryption. As the best RSA implementation of swift language, I suggest supporting it.

**Comment by paulw11** [comment]
I respectfully disagree. Other languages or frameworks may have implemented this but that doesn’t change the fact that it isn’t a secure use case of asymmetric key cryptography

**Comment by yanxiaobing** [comment]
> I respectfully disagree. Other languages or frameworks may have implemented this but that doesn’t change the fact that it isn’t a secure use case of asymmetric key cryptography

Thank you for sharing your work.

**Comment by riderx** [comment]
I do agree with @yanxiaobing i do use RSA encryption with privateKey and RSA decryption with Public key.
Our process is that way.
Our client encrypts a zip file with AES key, they AES key is then encrypted with the RSA private key.
The Encrypted ZIP is stored by us, and therefore cannot be altered by us.
We distribute the ZIP to the users of our client.
When they receive it with the encrypted AES key, they decrypt with the public key they have, and we never had in our hands.

We cannot use any SWIFT lib for that because you all think you are smarter than everyone else and not listen what are valid use case.

In Java and nodejs no problem with THIS

My user doesn't want me to know they code, of course if manage to fake get their client I could get the public key, to see what is inside what I host, but having this system protects my company legally as well as I'm not responsible I don't know what I host for them.
