### ISSUE TITLE
Use of unresolved identifier ‘ClearMessage’

### ISSUE THREAD

**Issue by sullivanv** [TakeScoop/SwiftyRSA#55]
Hi there,

I would like to use your lib because it perfectly fits my needs.
Nevertheless I am encountering an issue.

I installed it through cocoapod (v 0.5.0)
When used :
`let clear = try ClearMessage(string: "Clear Text", using: .utf8)
let encrypted = try clear.encrypted(with: publicKey, padding: .PKCS1)`
 I get this error:
Use of unresolved identifier ‘ClearMessage’

I have cleaned my project, restarted xcode but nothing works.
Any idea regarding this matter?
Thanks for your time

**Comment by DwightEverhart** [comment]
This is happening because ClearMessage is not in version 0.5.0. It's part of a refactor that was done after 0.5.0 was released. The refactored code hasn't been released, but the README has been updated to show how to use the new classes, leading to the confusion you (and I) experienced.

You can use the refactored code, if you want, by changing your podfile:

`pod 'SwiftyRSA', :git => 'https://github.com/TakeScoop/SwiftyRSA.git'`

**Comment by sullivanv** [comment]
Hey,

Thank you so much for your time. I really appreciate your help on this.
It did solve my issue.

Have a good day

**Comment by DwightEverhart** [comment]
You're welcome. I'm glad I could help.
