### ISSUE TITLE
Allow exporting the data back from PublicKey and PrivateKey

### ISSUE THREAD

**Issue by serieuxchat** [TakeScoop/SwiftyRSA#60]
Currently we can instantiate, e.g., a PublicKey with Data or a PEM string, but we cannot get these representations back if we already have a PublicKey.

It would be very useful if it were possible to at least get the raw data back.

**Comment by ldiqual** [comment]
This is a great idea. Exposing the key data is definitely an easy thing to do, we'll need to make sure that users understand that the data is not the exact data that was provided when creating the key – since we strip the headers when adding to the iOS keychain. We could potentially have `data` and `originalData` too.

As for PEM/DER, this is definitely something we can have too and that doesn't seem too hard to implement. PEM is just the key data in base64 with a header + footer, DER is raw bytes (so you could just use the `data` field).

I'm tagging this issue as `enhancement` and unless someone volunteers to PR something, I'll tackle it whenever I have an hour. Thanks a lot for the proposal!

**Comment by serieuxchat** [comment]
Thanks very much for your quick reply!

**Comment by ldiqual** [comment]
@serieuxchat With https://github.com/TakeScoop/SwiftyRSA/commit/5485e6a584efa157bfb552445ca98ed4ed81fad2 , SwiftyRSA now gives you readonly access to `reference`, `data` and `dataWithoutHeader` (public key only). You can check it out this way:

```
pod 'SwiftyRSA', :git => 'git@github.com:TakeScoop/SwiftyRSA.git', :branch => 'master'
```

I'll incrementally add support for exporting to PEM/DER and init with a SecKey. Thanks a lot for your patience!

**Comment by ldiqual** [comment]
@serieuxchat I PR'd some code that adds support for `data()`, `pemString()` and `base64String()` here: https://github.com/TakeScoop/SwiftyRSA/pull/61. Feel free to jump in if you have any comment!

**Comment by serieuxchat** [comment]
Thanks a lot! We will give it a try.

**Comment by ldiqual** [comment]
@serieuxchat Good news! SwiftyRSA 1.1.0 has been pushed to cocoapods and now allows exporting data from a private or public key. Let me know if you run into any issue! Closing this now
