### ISSUE TITLE
How to decrypt data with Public Key?

### ISSUE THREAD

**Issue by 4taras4** [TakeScoop/SwiftyRSA#79]
Library support  only encryption with public key and what about decrypt?

**Comment by Flo354** [comment]
You decrypt data with private key, not with public key.

**Comment by paulw11** [comment]
As @Flo354 said, you encrypt data with the public key and decrypt it with the private key.  If two parties want to communicate securely then you either use two public/private key pairs or, more typically, use a single public-private key pair to exchange a key for a symmetric cipher and then use that cipher to communicate.  

SwiftyRSA supports signature verification with a public key, so the private key holder can generate a signed message and someone with the public key can verify that signature and validate that the message was sent by the holder of the private key

**Comment by FXLynn** [comment]
if server encrypt data with  private key，how can i decrypt it with public key ？

**Comment by 4taras4** [comment]
using swifty RSA

**Comment by FXLynn** [comment]
i am new use swiftyRSA  can you show me the code? thanks

**Comment by FXLynn** [comment]
i can't  find the api

**Comment by soulwell32** [comment]
same problem, i need to decrypt serverData with public key.

**Comment by paulw11** [comment]
As I said above, decrypting data with a public key is not how it works.  If you think about it, you might as well just send the data in the clear, since anyone who has the public key can decrypt it; and the public key is exactly that, public; so anyone can have it.

What does make sense is to decrypt some data that was encrypted with the private key with the public key, in order to verify that the sender does, in fact, possess the private key
